name: Build and Publish
on: [ push, pull_request ]
jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:

      # Setup Java 1.8 environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v2.3.1

      # Build application
      - name: Test and Build
        run: ./gradlew :web-app:build

      # If main branch update, deploy to gh-pages
      - name: Deploy
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/KMP'
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          repository-name: Shabinder/SpotiFlyer
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: web-app/build/distributions # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
